spring:
    datasource:
        url: jdbc:mysql://localhost/tmp_info?characterEncoding=UTF-8
        username: tmp_info_user
        password: 123456
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
                ddl-auto: update

logging:
    level:
        org.springframework.transaction: DEBUG